### ISSUE TITLE
java.lang.IllegalArgumentException when trying to deserialize a map

### ISSUE THREAD

**Issue by iad24** [square/moshi#410] opened 2017-12-12 17:50 UTC
I have this model:

```
    class Model1 {
      	<... other fields here ...>
        var attributes: Map<String, Any>? = null
        <... other fields here ...>
    }
```

I expect a list of these models.

Sample JSON:

```
    [
    	{
    		"attributes": {
    			"title": "New Year's Day",
    			"country": "SG"
    		}
    	},
    	{
    		"attributes": {
    			"staff_id": 320011,
    			"title": "Labor day",
    			"date_joined": "2017-01-10 00:00:00",
    			"years": 1
    		}
    	}
    ]
```

Then I get this error during deserialization:

 ```
   Caused by: java.lang.IllegalArgumentException: Expected a Class, ParameterizedType, or GenericArrayType, but <null> is of type null
    	at com.squareup.moshi.Types.getRawType(Types.java:165)
    	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:82)
    	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:74)
    	at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
    	at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
    	at com.squareup.moshi.MapJsonAdapter.<init>(MapJsonAdapter.java:46)
    	at com.squareup.moshi.MapJsonAdapter$1.create(MapJsonAdapter.java:37)
    	at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
    	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:90)
    	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:74)
    	at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
    	at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
    	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:51)
    	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:35)
    	at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
    	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:90)
    	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:74)
    	at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
    	at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:91)
    	at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
    	at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
    	at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:736)
    		... 65 more
```

I need the field attribute to be a map. The data inside could be any type and any value

I create my Retrofit like this:
```
Retrofit.Builder().baseUrl(baseUrl)
.addConverterFactory(MoshiConverterFactory.create())
.client(httpClient.build())
.build()
```

**Comment by JakeWharton** [comment] 2017-12-12 17:54
Dupe of #404. You can add `@JvmSuppressWildcards` for a workaround.

**Closed by JakeWharton** 2017-12-12 17:54 UTC

**Comment by iad24** [comment] 2017-12-12 18:12
@JakeWharton ur the man

To others, do it this way:
```
class Model1 {
      	<... other fields here ...>
        @JvmSuppressWildcards var attributes: Map<String, Any>? = null
        <... other fields here ...>
    }
```

**Comment by mzander** [comment] 2018-03-14 07:23
I dont know why buy this workaround does not solve the problem for me.

My data class:
```
data class PartialStatusWrapper<T>(
        @Json(name = "status")
        var status: Int = 0,

        @Json(name = "data")
        @JvmSuppressWildcards var data: T? = null,

        @Json(name = "error")
        var error: ResponseError? = null
)
```

that is how I build the moshi client

```
Moshi.Builder()
                .add(KotlinJsonAdapterFactory())
                .add(Date::class.java, Rfc3339DateJsonAdapter().nullSafe())
                .add(Uri::class.java, UriJsonAdapter().nullSafe())
                .add(ContactAdapter())
                .build()
```

and I still get the same exception as @iad24

**Comment by NightlyNexus** [comment] 2018-03-14 07:46
@mzander that's #309.
by the way, install the KotlinJsonAdapterFactory last to let any custom JsonAdapters take precedence.
