### ISSUE TITLE
Nesting too deep error thrown

### ISSUE THREAD

**Issue by nicusorflorin** [square/moshi#407] opened 2017-12-04 07:00 UTC
This is really annoying, especially since there are 3 pull requests open to fix this: #329 #349 #350

 `What went wrong:
Execution failed for task ':graphql-module:generateDebugApolloClasses'.

Nesting too deep at $.operations[2].fields[0].fields[1].fields[3].fields[2].fields[4].fields[3].fields[3].fields[2].fields[4].fields[3].fields[3].fields[2].fields[4].fields[3].fields
Caused by: com.squareup.moshi.JsonDataException: Nesting too deep at $.operations[2].fields[0].fields[1].fields[3].fields[2].fields[4].fields[3].fields[3].fields[2].fields[4].fields[3].fields[3].fields[2].fields[4].fields[3].fields
at com.squareup.moshi.JsonReader.pushScope(JsonReader.java:203)
at com.squareup.moshi.JsonUtf8Reader.beginArray(JsonUtf8Reader.java:107)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:74)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:39)
`

**Comment by NightlyNexus** [comment] 2017-12-04 07:28
Duplicate of #348. It's best if we can track a single feature request in a single place. Feel free to give a thumbs up reaction there, so people can know if it's a common use case, or comment if you have additional information or use cases to provide.

**Closed by NightlyNexus** 2017-12-04 07:28 UTC

**Comment by nicusorflorin** [comment] 2017-12-04 10:26
Thumbed up, but i see it has a pull request addressing it created 3 months  ago and it is approved and not yet merged
