### ISSUE TITLE
Custom type adapters for value/inline classes aren't used

### ISSUE THREAD

**Issue by saket** [square/moshi#1587] opened 2022-11-11 08:00 UTC
Moshi (1.14.0) is failing to find custom type adapters for value classes. Is this expected?

```
java.lang.IllegalArgumentException: Cannot serialize Kotlin type me.saket.example.Bar. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:98)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:75)
	at com.squareup.moshi._MoshiKotlinExtensionsKt.adapter(-MoshiKotlinExtensions.kt:40)
```

Here's a reproducible test:

```kotlin
class FooTest {
  @Test fun `foo`() {
    val moshi = Moshi.Builder()
      .add(BarMoshiAdapter())
      .build()

    val json = moshi.adapter<Bar>().toJson(Bar("foo"))
    println(json)
    check(json == "\"foo\"")
  }
}

@JvmInline
value class Bar(val value: String)

class BarMoshiAdapter {
  @ToJson fun toJson(id: Bar): String = id.value
  @FromJson fun fromJson(id: String): Bar = Bar(id)
}
```

My understanding is that `AdapterMethod#type` is incorrectly resolved as `String` for `BarMoshiAdapter`, which prevents [AdapterMethodsFactory#L318](https://github.com/square/moshi/blob/6e1d6091133e437e95163994ec3befc663d08f4d/moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java#L318) from being able to find the adapter.

I'm currently working around this by changing `Bar` to a data class.

**Comment by ZacSweers** [comment] 2022-11-11 08:02
Dupe of #1170

**Closed** 2022-11-11 08:02 UTC
Labels: bug

**Comment by ZacSweers** [comment] 2022-11-11 08:04
Actually not even, AdapterMethodsFactory is purely java reflection and couldn't know about the inline class param in this case
