### ISSUE TITLE
Support for recursive PolymorphicJsonAdapterFactory

### ISSUE THREAD

**Issue by ursusursus** [square/moshi#1347] opened 2021-05-19 00:24 UTC
I have a sealed class hierarchy which looks like this 

```kotlin
sealed class Status {
    sealed class HasBonus : Status() {
        abstract val bonus: Double

        data class Active(override val bonus: Double) : HasBonus()
        data class Eligible(val id: String, override val bonus: Double) : HasBonus()
        data class MissingConsumer(override val bonus: Double) : HasBonus()
        data class MissingContributor(override val bonus: Double) : HasBonus()
    }

    object NotEligible : Status()
}
```

I think this should work

```kotlin
PolymorphicJsonAdapterFactory.of(Mcc.Status::class.java, "type")
        .withSubtype(Mcc.Status.HasBonus::class.java, "has_bonus")
        .withSubtype(Mcc.Status.NotEligible::class.java, "not_eligible")
```

```kotlin
PolymorphicJsonAdapterFactory.of(Mcc.Status.HasBonus::class.java, "bonus_type")
        .withSubtype(Mcc.Status.HasBonus.Active::class.java, "active")
        .withSubtype(Mcc.Status.HasBonus.Eligible::class.java, "eligible")
        .withSubtype(Mcc.Status.HasBonus.MissingConsumer::class.java, "missing_consumer")
        .withSubtype(Mcc.Status.HasBonus.MissingContributor::class.java, "missing_contributor")
```

But fails at runtime with 

```
 java.lang.IllegalArgumentException: Expected one of [class sk.o2.mojeo2.mcc.data.Mcc$Status$HasBonus, class sk.o2.mojeo2.mcc.data.Mcc$Status$NotEligible] but found Eligible(id=ID:SOME:PRODUCT, bonus=20.0), a class sk.o2.mojeo2.mcc.data.Mcc$Status$HasBonus$Eligible. Register this subtype.
        at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.toJson(PolymorphicJsonAdapterFactory.java:307)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at sk.o2.mojeo2.mcc.data.Mcc_StatusJsonAdapter.toJson(Mcc_StatusJsonAdapter.kt:33)
        at sk.o2.mojeo2.mcc.data.Mcc_StatusJsonAdapter.toJson(Mcc_StatusJsonAdapter.kt:15)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:82)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:90)
```

(Continuation of https://github.com/ZacSweers/MoshiX/issues/117)

**Comment by ZacSweers** [comment] 2021-09-26 17:31
Dupe of #1340

**Closed by ZacSweers** 2021-09-26 17:31 UTC
Labels: enhancement
