### ISSUE TITLE
Inline class in constructor with default leads to exception: Kotlin Codegen

### ISSUE THREAD

**Issue by Wasabi375** [square/moshi#998] opened 2019-11-01 23:33 UTC
```kotlin
inline class Inline(val i: Int)
@JsonClass(generateAdapter = true)
class InlineConsumer(val i: Inline = Inline(42)
```
This leads to a exception when deserializing an `InlineConsumer`. The problem is that the generated constructor call uses reflection. 
The adapter tries to find the constructor based on the types of the arguments. The argument in this case is `Int`(it is inlined), but the current version of moshi looks for `Inline`. 
Also when passing the inline object to the constructor it needs to be unwrapped to `Int` or it will lead to a typecast exception.
I fixed this in a branch here: 353a86dff0fa27c8719f3840cb06636bd368c09d, but the fix is kinda hacky and should probably not be used in a proper release, so I wouldn't merge it.
The problematic part is figuring out which types to inline. I do this by checking the jvm signature of the getter of each property and comparing this to the `returnType` of `ImmutableKmProperty`. I use the same system to get the inlined type. This should at least be properly refactored (maybe needs support by kotlinpoet).
___
PS: This is the issue I mention a few days ago. So I hope it's the last I submit (at least in the near future :wink:)
PPS: I know inline classes are not officaly supported by moshi, but tracking this is still useful for the future.

**Comment by swankjesse** [comment] 2020-09-26 02:43
Duplicate of https://github.com/square/moshi/issues/1170

**Closed by swankjesse** 2020-09-26 02:43 UTC
Labels: Kotlin - code gen
