### ISSUE TITLE
Cannot build with moshi-kotlin-codegen

### ISSUE THREAD

**Issue by gellertbiro** [square/moshi#804] opened 2019-02-01 13:57 UTC
I am not sure this issue is 100% Moshi related, but I've recently decided to give a try to the Adapter generation. I set up correctly everything to use generated adapters. The funny thing is that it is working on my local machine which is a Mac, but when my CI tried to build the project, the build wasn't successful. (The CI running on Linux)

This is the error message:
```
Could not resolve all files for configuration ':core:kapt'.
  > Failed to transform artifact 'kotlin-compiler-embeddable.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.71)' to match attributes {artifactType=processed-jar, org.gradle.usage=java-runtime-jars}
     > Execution failed for JetifyTransform: /root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.71/a79f934bfbc1c7e16638da3474feab351735f1c0/kotlin-compiler-embeddable-1.2.71.jar.
        > Failed to transform '/root/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.71/a79f934bfbc1c7e16638da3474feab351735f1c0/kotlin-compiler-embeddable-1.2.71.jar' using Jetifier. Reason: Malformed input or input contains unmappable characters: javaslang/?.class. (Run with --stacktrace for more details.)
```
If I delete this line:
```
    kapt "com.squareup.moshi:moshi-kotlin-codegen:$moshiVersion"
```
then the CI can build my project, but of course, I cannot use the generated adapters. Again, sorry if this is off-topic, but do you have any idea why is this happening?

**Comment by brozikcz** [comment] 2019-02-22 16:14
Hi,

we have same problem.

`17:11:36 * What went wrong:
17:11:36 Execution failed for task ':lib-pojos:kaptGenerateStubsStagingDebugKotlin'.
17:11:36 > Could not resolve all files for configuration ':lib-pojos:kapt'.
17:11:36    > Failed to transform file 'kotlin-compiler-embeddable-1.2.71.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
17:11:36       > Failed to transform '/home/jenkins/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.71/a79f934bfbc1c7e16638da3474feab351735f1c0/kotlin-compiler-embeddable-1.2.71.jar' using Jetifier. Reason: Malformed input or input contains unmappable characters: javaslang/?.class. (Run with --stacktrace for more details.)
17:11:36 
17:11:36 * Try:
17:11:36 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
17:11:36 
17:11:36 * Exception is:
17:11:36 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':lib-pojos:kaptGenerateStubsStagingDebugKotlin'.
17:11:36 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:49)
17:11:36 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
17:11:36 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
17:11:36 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
17:11:36 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
17:11:36 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
17:11:36 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
17:11:36 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
17:11:36 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
17:11:36 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
17:11:36 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
17:11:36 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
17:11:36 	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
17:11:36 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
17:11:36 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
17:11:36 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
17:11:36 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
17:11:36 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
17:11:36 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
17:11:36 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
17:11:36 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
17:11:36 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
17:11:36 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
17:11:36 Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':lib-pojos:kapt'.
17:11:36 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1054)
17:11:36 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:123)
17:11:36 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1028)
17:11:36 	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:76)
17:11:36 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:439)
17:11:36 	at org.gradle.api.internal.file.CompositeFileCollection.iterator(CompositeFileCollection.java:65)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.SubpluginUtilsKt$withWrappedKaptOptions$1.apply(subpluginUtils.kt:75)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.SubpluginUtilsKt$withWrappedKaptOptions$1.apply(subpluginUtils.kt)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.SubpluginUtilsKt.withWrappedKaptOptions(subpluginUtils.kt:50)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask.setupCompilerArgs(KaptGenerateStubsTask.kt:78)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask.setupCompilerArgs(KaptGenerateStubsTask.kt:36)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.CompilerArgumentAware$DefaultImpls.setupCompilerArgs$default(CompilerArgumentAware.kt:37)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.CompilerArgumentAwareKt.prepareCompilerArguments(CompilerArgumentAware.kt:41)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.CompilerArgumentAware$DefaultImpls.getFilteredArgumentsMap(CompilerArgumentAware.kt:34)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.CompilerArgumentAwareWithInput$DefaultImpls.getFilteredArgumentsMap(CompilerArgumentAware.kt:54)
17:11:36 	at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompileTool.getFilteredArgumentsMap(Tasks.kt:50)
17:11:36 	at org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask_Decorated.getFilteredArgumentsMap(Unknown Source)
17:11:36 	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:83)
17:11:36 	at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:313)
17:11:36 	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:80)
17:11:36 	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
17:11:36 	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue.getValue(AbstractNestedRuntimeBeanNode.java:138)
17:11:36 	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue.validate(AbstractNestedRuntimeBeanNode.java:149)
17:11:36 	at org.gradle.api.internal.tasks.DefaultTaskInputPropertySpec.validate(DefaultTaskInputPropertySpec.java:61)
17:11:36 	at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.validate(DefaultTaskProperties.java:193)
17:11:36 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
17:11:36 	... 26 more
17:11:36 Caused by: org.gradle.api.artifacts.transform.ArtifactTransformException: Failed to transform file 'kotlin-compiler-embeddable-1.2.71.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
17:11:36 	at org.gradle.api.internal.artifacts.transform.UserCodeBackedTransformer.transform(UserCodeBackedTransformer.java:90)
17:11:36 	at org.gradle.api.internal.artifacts.transform.TransformArtifactOperation.run(TransformArtifactOperation.java:51)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.access$900(DefaultBuildOperationExecutor.java:48)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$ParentPreservingQueueWorker.execute(DefaultBuildOperationExecutor.java:343)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:230)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.access$600(DefaultBuildOperationQueue.java:172)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:209)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:203)
17:11:36 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:203)
17:11:36 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:177)
17:11:36 	... 3 more
17:11:36 Caused by: java.lang.RuntimeException: Failed to transform '/home/jenkins/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.71/a79f934bfbc1c7e16638da3474feab351735f1c0/kotlin-compiler-embeddable-1.2.71.jar' using Jetifier. Reason: Malformed input or input contains unmappable characters: javaslang/?.class. (Run with --stacktrace for more details.)
17:11:36 	at com.android.build.gradle.internal.dependency.JetifyTransform.transform(JetifyTransform.kt:243)
17:11:36 	at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:44)
17:11:36 	at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:29)
17:11:36 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:251)
17:11:36 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:238)
17:11:36 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:91)
17:11:36 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:87)
17:11:36 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.doAdd(DefaultPathKeyFileStore.java:137)
17:11:36 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.doAdd(DefaultPathKeyFileStore.java:127)
17:11:36 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:87)
17:11:36 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:50)
17:11:36 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:163)
17:11:36 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:142)
17:11:36 	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:90)
17:11:36 	at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:193)
17:11:36 	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:170)
17:11:36 	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:195)
17:11:36 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:142)
17:11:36 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:135)
17:11:36 	at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
17:11:36 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.loadIntoCache(DefaultTransformedFileCache.java:135)
17:11:36 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.getResult(DefaultTransformedFileCache.java:127)
17:11:36 	at org.gradle.api.internal.artifacts.transform.UserCodeBackedTransformer.transform(UserCodeBackedTransformer.java:88)
17:11:36 	... 16 more
17:11:36 Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: javaslang/?.class
17:11:36 	at com.android.tools.build.jetifier.processor.archive.Archive$Builder.extractArchive(Archive.kt:159)
17:11:36 	at com.android.tools.build.jetifier.processor.archive.Archive$Builder.extract(Archive.kt:142)
17:11:36 	at com.android.tools.build.jetifier.processor.archive.Archive$Builder.extract$default(Archive.kt:137)
17:11:36 	at com.android.tools.build.jetifier.processor.Processor.loadLibraries(Processor.kt:314)
17:11:36 	at com.android.tools.build.jetifier.processor.Processor.transform(Processor.kt:201)
17:11:36 	at com.android.build.gradle.internal.dependency.JetifyTransform.transform(JetifyTransform.kt:238)
17:11:36 	... 38 more`

**Comment by plastiv** [comment] 2019-02-22 16:25
You could try to blacklist  kotlin compiler dependency from jettifier with `gradle.properties`

```
android.jetifier.blacklist = kotlin-compiler-embeddable-.*\\.jar
```

**Comment by gellertbiro** [comment] 2019-02-22 16:43
I disabled the Jetifier fully, since we don't have any third party with old UI dependecies. It solved the problem.

**Comment by dudududi** [comment] 2019-02-25 09:03
I have also encountered the same problem, resolved it by exposing `$LANG` environment variable in Dockerfile used on CI:
```
ENV LANG=en_US.utf8
```
... and works like a charm ;)

**Comment by hantrungkien** [comment] 2019-06-17 15:44
https://stackoverflow.com/a/54325765/4411879

**Comment by ZacSweers** [comment] 2019-06-18 05:43
Going to close this out and suggest using @plastiv's solution or filing a bug on Jetifier, as this doesn't seem to be a moshi issue directly

**Closed by ZacSweers** 2019-06-18 05:43 UTC
