### ISSUE TITLE
Does not handle @Json(name = "object")

### ISSUE THREAD

**Issue by MKevin3** [square/moshi#1458] opened 2021-12-11 17:55 UTC
I don't have control over the REST API but I get back JSON using "object" as the key. Moshi seems to get confused when this is the case and parses nothing i.e. I get a null.

```
data class AssetTagResponse(
    @Json(name = "object")
    val assetTagData: AssetTagData
)

```
This always returns a NULL for assetTagData

The JSON from the server looks like this
```
{ "object": { "totalRecords": :10   and so on
```
I am converting from GSON to Moshi for this project. GSON handled this just fine as @SerializedName but changing it to @Json seems to confuse the Moshi parser.

**Comment by ZacSweers** [comment] 2021-12-12 00:18
Can you create a minimally reproducible sample? That’s not enough context to diagnose

**Comment by MindaugasVarkalys** [comment] 2021-12-21 11:03
This is happening only on Kotlin version `1.6.*` when building a release version of the Android app with `minifyEnabled true`. As a temporary workaround you can lower Kotlin version to `1.5.31` and it will solve the problem.

**Comment by ZacSweers** [comment] 2021-12-21 18:01
Again

> Can you create a minimally reproducible sample? That’s not enough context to diagnose

I'm closing this for now, feel free to revisit with the above

**Closed by ZacSweers** 2021-12-21 18:01 UTC

**Comment by MKevin3** [comment] 2021-12-21 22:01
Thanks for the update, I will retry my GSON -> MOSHI conversion in the near future with this in mind.

**Comment by arturdryomov** [comment] 2021-12-22 07:58
@ZacSweers, we observe a similar behavior. [The sample](https://github.com/square/moshi/files/7760933/moshi-sample.zip) (a ZIP file). However, I’m not sure if it’s a Kotlin issue, an R8 issue or a Moshi issue.

Steps to reproduce:

1. Install the application via `./gradlew installDebug`.
2. Launch the application called _Moshi Sample_.
3. The application gonna crash on launch since there is an `assert`. Relevant bits are at the `MoshiApplication.kt` file.
4. Replace all `1.6.0` mentions in the `build.gradle` file with `1.5.31`.
5. Repeat steps 1 and 2.
6. The application not gonna crash since the `assert` is successful.

This happens if the name in the `@Json` annotation is different from the field name _and_ the Kotlin version is 1.6.0. Under these conditions Moshi writes `null` to the field as if it doesn’t exist in the JSON. It feels like the `@Json` annotation is stripped away when Kotlin 1.6.0 is involved.

**Comment by ZacSweers** [comment] 2021-12-22 08:34
If debug builds work fine and it only happens with R8, I don't really see how this is a Moshi issue 🤔. Especially if the trigger for it is changing the kotlin version (but not the Moshi version?). I'll look at the sample when I can but I suspect there's nothing really for us to do here. This also sounds like something pretty easy to verify yourself - does the generated code appear to use the wrong json name, is R8 shrinking it away in the final APK, etc

**Comment by arturdryomov** [comment] 2021-12-22 08:42
Yeah, it sounds more of an R8 issue to me. I’m afraid this might become a ping-pong game of the R8 team sending us to the Kotlin team and the Kotlin team sending us to you and to R8 again 🙈 If it’s possible to help with pinpointing an issue — it would be super helpful.

**Comment by MindaugasVarkalys** [comment] 2021-12-27 19:51
This is a bug in Android Gradle Plugin. A fix can be found here:
https://stackoverflow.com/a/70331139/4167198

> What turned out to be the issue is that R8 bundeled with AGP 7.0 (release with Android Studio - Arctic Fox) does not handle Kotlin metadata correctly for Kotlin 1.6.0.
>
>If using Kotlin 1.6.0 (classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0") with AGP 7.0, then R8 version 3.0.77 is required for shrinking Kotlin libraries and for using kotlin-reflect. Updating to AGP 7.0.4 is not enough, as that version is bundled with R8 3.0.76.
>
>To use R8 3.0.77 add the following to your settings.gradle or settings.gradle.kts:
>
>```
>pluginManagement {
>    buildscript {
>        repositories {
>            mavenCentral()
>            maven {
>                url = uri("https://storage.googleapis.com/r8-releases/raw")
>            }
>        }
>
>        dependencies {
>            classpath("com.android.tools:r8:3.0.77")
>            classpath('com.google.guava:guava:30.1.1-jre')
>        }
>    }
>}
>```
>Another option for AGP 7.0 is to use Kotlin 1.5.31.
>
>Also consider aligning your version of kotlin-reflect with the version of the Kotlin compiler.
