### ISSUE TITLE
Unable to use KotlinJsonAdapterFactory with desugaring

### ISSUE THREAD

**Issue by vmtrue** [square/moshi#1169] opened 2020-07-06 12:35 UTC
Is there any way to use `KotlinJsonAdapterFactory` with desugaring? 

Desugaring renames the package name ( `java.time.LocalDateTime `->` j$.time.LocalDateTime` ) so that I get 
`java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime"`

example:

```
    data class Foo(val date: LocalDateTime?)

    fun test() {
        val moshi = Moshi.Builder()
            .add(KotlinJsonAdapterFactory())
            .build()

        val adapter = moshi.adapter<Foo>(Foo::class.java)
        print(adapter)
    }
```

**Comment by JakeWharton** [comment] 2020-07-06 13:31
Probably caused by https://issuetracker.google.com/issues/158124557. You can add R8 version 2.0.85 (or newer) to your Gradle buildscript classpath **before** the Android Gradle plugin to test the fix.

**Comment by JakeWharton** [comment] 2020-07-06 13:43
Or it might be the same bug but for Kotlin metadata, actually...

**Comment by ZacSweers** [comment] 2020-07-29 04:19
Pretty sure this is because L8 is not rewriting the `@Metadata` annotation data. I filed a separate issue here: https://issuetracker.google.com/issues/162259266

CC @jsjeon

**Comment by jsjeon** [comment] 2020-07-29 17:00
Thank you for looping me in. I handed over `@Metadata` rewriting to someone else, and he will response to the new issue once he is back from vacation (probably early next week).

Meanwhile, we can double-check versions. @vmtrue could you check what AGP and/or R8 version you were using?

I wonder, though, it's likely the dup of the issue @JakeWharton mentioned. As per https://issuetracker.google.com/issues/158124557#comment17, the patch didn't make it to AGP 4.0.0, and would be available for the next point release if any.

**Comment by vmtrue** [comment] 2020-08-25 08:00
Hi @jsjeon,
I tried with AGP 4.0.0 but the same result with AGP 4.0.1

**Comment by jsjeon** [comment] 2020-08-25 18:34
Thanks for the update. Since the patch for https://issuetracker.google.com/issues/158124557 didn't make it to AGP 4.0.0, there won't be any difference between 4.0.0 and 4.0.1 perhaps.

But it looks like that's not the root cause, and the separate issue @ZacSweers filed, https://issuetracker.google.com/issues/162259266, _is_ the issue. A fix is just checked in to the master 1 week ago, so I guess the next _canary_ release will begin to include it (which means... a long way to a stable release is waiting...). You can ask the timeline directly to that issue.

**Comment by swankjesse** [comment] 2020-09-26 01:59
No action to take on this.

**Closed by swankjesse** 2020-09-26 01:59 UTC

**Comment by man-trifork** [comment] 2021-04-01 09:21
I have the same issue with `AGP 4.2.0-beta04` on devices  < API 26.

![image](https://user-images.githubusercontent.com/58421983/113269877-2f0ef500-92d9-11eb-9dd8-c3ae7512d11a.png)


That happens at:

```
class User(
  ....
  ....
  val createdDate: Instant,
  @Transient
  override val userRegistrationDate: Instant? = createdDate,
): IUser

val json = moshi.adapter(User::class.java).toJson(user)
```
