### ISSUE TITLE
Polymorphic class that has member with the same name as the labelKey will have labelKey serialized twice

### ISSUE THREAD

**Issue by BenSchwab** [square/moshi#1367] opened 2021-07-28 06:57 UTC
If a polymorphic class repeats `labelKey` as in:

```
interface Hand

data class BlackjackHand(@Json(name = "score") val score: Int, @Json(name = "hand_type") val type: String) : Hand

val handAdapter: PolymorphicJsonAdapterFactory<Hand> = PolymorphicJsonAdapterFactory.of(Hand::class.java, "hand_type")
    .withSubtype(BlackjackHand::class.java, "blackjack")
    .withSubtype(PokerHand::class.java, "holdem")
```
the json will have the label key twice (in this case "hand_type").

When combined with a KotlinJsonFactory, which [fails](https://github.com/BenSchwab/moshi/blob/master/kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt#L79) on duplicate properties, this can result in serializing a class, followed by deserializing causing a crash.

Demo of the duplicate serialization (the test will fail with type being serialized twice):
https://github.com/square/moshi/compare/master...BenSchwab:bschwab--serialization-issue?expand=1

**Comment by ZacSweers** [comment] 2021-08-01 19:01
Dupe of #874

**Closed by ZacSweers** 2021-08-01 19:01 UTC
Labels: bug
