### ISSUE TITLE
nullsafe not support when use Generics in kotlin

### ISSUE THREAD

**Issue by WangJie0822** [square/moshi#1283] opened 2020-12-24 06:34 UTC
```
data class TestEntity(
    val data: List<String>
)

val json = """
    {
        "data": [null, "aa"]
    }
""".trimIndent()

val result = Moshi.Builder().addLast(KotlinJsonAdapterFactory()).build().adapter(TestEntity::class.java).fromJson(json)
println(result)

> TestEntity(data=[null, aa])

result.data[0].length > throw NullPointerException
````
* The **String** in the **List** is declared as non-null, but the data parsed from json can be null, and the NullPointerException will not be thrown until it is used.

**Comment by ZacSweers** [comment] 2020-12-24 09:22
Dupe of #634

**Closed** 2020-12-24 15:46 UTC
