### ISSUE TITLE
Unexpected duplicated values on serialization with PolymorphicJsonAdapterFactory

### ISSUE THREAD

**Issue by Artman12** [square/moshi#1432] opened 2021-11-25 08:49 UTC
Tested in version `1.12.0`

```
abstract class BaseData

data class Data1(
    @Json(name = "type") val dataType: String,
) : BaseData()

data class Wrapper(
    @Json(name = "data") val data: BaseData,
)

class DataTester {
    fun test() {
        val wrapper = Wrapper(Data1("data1"))

        val builder = Moshi.Builder()
            .add(getDataFactory())
            .add(KotlinJsonAdapterFactory())
            .build()
        val json = builder.adapter(Wrapper::class.java).toJson(wrapper)
        Log.i("!!!!!!!!", "json: " + json);
    }

    private fun getDataFactory() : JsonAdapter.Factory {
        return PolymorphicJsonAdapterFactory.of(BaseData::class.java, "type")
            .withSubtype(Data1::class.java, "data1")
    }
}
```

When executing `DataTester().test()` I see duplicated `type` key-value pairs for `data` object. It looks like a bug

Here's Log output:
`I/!!!!!!!!: json: {"data":{"type":"data1","type":"data1"}}`

This is big issue for me because I wanted to use serialization to clone a very complex object, but the conversion back from json 
causes `java.lang.RuntimeException: Unable to create application com.test.test.testApplication: com.squareup.moshi.JsonDataException: Multiple values for 'dataType' at $.data.type`

I try to use following code to convert back to object:
```
val wrapperClone = builder.adapter(Wrapper::class.java).fromJson(json)!!
```

Also is there a possible workaround I could use to create a clone object using Moshi?

**Comment by ZacSweers** [comment] 2021-11-25 21:07
Dupe of #874, please search for existing issues first

**Closed** 2021-11-25 21:07 UTC
Labels: bug
