### ISSUE TITLE
Skipping wrappers

### ISSUE THREAD

**Issue by konmik** [square/moshi#1091] opened 2020-02-07 13:40 UTC
I have a tiny feature request! Very often I have my model wrapped into a series of wrappers BE developers created for some reasons. Typically it is something like `{ #RCall#0: { payload: { result: { success: true } } } }`.

Right now it requires for me to create many wrapping classes and use generics if I don't want to repeat this stuff for each request.

Could it be that a nice and simple solution for this actually lies on library level?

```
data class LoginResponse(
    @Json(path = "#RCall#0.payload.result", name = "success")
    val success: Boolean
)
```

**Comment by JakeWharton** [comment] 2020-02-07 13:42
Probably a dupe of #1051.

**Comment by konmik** [comment] 2020-02-07 13:50
You are right, it is.

**Closed** 2020-04-10 01:06 UTC
