### ISSUE TITLE
Generic Kotlin data classes cannot be (de)serialized

### ISSUE THREAD

**Issue by svenjacobs** [square/moshi#309] opened 2017-05-18 08:45 UTC
It seems that Moshi 1.5.0 has a problem with (de)serialization of generic data classes.

```kotlin
data class Test<out T>(val item: T)

data class Test2(val test: Test<String>)
```

The following code

```kotlin
val json = """{test:{item:"hello"}}"""
val moshi = Moshi.Builder()
        .add(KotlinJsonAdapterFactory())
        .build()
val data = moshi.adapter(Test2::class.java).fromJson(json)
```

produces the exception

```
java.lang.IllegalArgumentException: Expected a Class, ParameterizedType, or GenericArrayType, but <null> is of type null
  at com.squareup.moshi.Types.getRawType(Types.java:167)
  at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:83)
  at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:75)
  at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
  at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
  at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
  at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
  at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
  at com.squareup.moshi.Moshi.adapter(Moshi.java:62)
  at com.svenjacobs.test.components.main.view.MainActivity.onCreate(MainActivity.kt:24)
```

This was working in Moshi 1.4.0 and before.

**Comment by swankjesse** [comment] 2017-05-18 11:23
Can fix.

**Comment by fmrsabino** [comment] 2017-05-30 22:43
Not sure if related but I'm also getting the same issue using Lists. As an example:

```kotlin
data class PaginatedResponse<out T>(val page: Int, val results: List<T>)
```

**Comment by thatJavaNerd** [comment] 2017-06-18 00:18
Is there a suggested workaround until this issue gets fixed?

**Comment by fmrsabino** [comment] 2017-06-18 11:54
@thatJavaNerd I reverted to version `1.4.0`

**Comment by cre8ivejp** [comment] 2017-07-26 10:19
Anyone knows when the PR above fixing this issue will be merged?

Thanks.

**Comment by swankjesse** [comment] 2017-08-01 01:55
I think it’s too simple. Will try to find time for it.

**Comment by rodly** [comment] 2017-08-28 20:21
@swankjesse Is this fix being worked on still?

**Comment by swankjesse** [comment] 2017-08-28 22:24
Yep.

**Comment by mradzinski** [comment] 2017-10-30 15:22
@swankjesse Any news regarding this? Just wondering if to use Moshi 1.4.0 while this is fixed.

**Comment by ishitatsuyuki** [comment] 2017-11-08 10:03
Ping, this issue is quite critical.

**Comment by mhf-air** [comment] 2017-12-24 06:29
Please fix this

**Comment by blackberry2016** [comment] 2018-01-18 09:56
The same problem.
```java
data class Note constructor(@Json(name = "note_title") var title: String?,
                            @Json(name = "note_star") var star: Long,
                            @Json(name = "note_content") var content: String?)

data class Page<T> constructor(@Json(name = "my_list") var list: List<T>)
```
The following code
```java
@JvmOverloads
fun toJson(obj: Any, type: Type, moshi: Moshi? = null): String {
    val mMoshi = moshi ?: Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
    return mMoshi.adapter<Any>(type).lenient().toJson(obj)
}


val list = listOf(
                Note("note 1", 1024L, "Learn more, sleep more, and eat more-1"),
                Note("note 2", 512L, "Learn more, sleep more, and eat more-2"),
                Note("note 3", 72L, "Learn more, sleep more, and eat more-3"))

toJson(Page(list), Types.newParameterizedType(Page::class.java, Note::class.java))
```
exception
```java
java.lang.IllegalArgumentException: Expected a Class, ParameterizedType, or GenericArrayType, but <null> is of type null

	at com.squareup.moshi.Types.getRawType(Types.java:167)
	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:83)
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:75)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
	at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
```

**Comment by blackberry2016** [comment] 2018-01-31 08:11
Is this bug maintained now?

**Comment by blackberry2016** [comment] 2018-02-01 03:26
Is this bug maintained by now?

**Comment by LouisCAD** [comment] 2018-02-08 15:29
I guess the issue is not present in kotshi as this fixed issue shows: https://github.com/ansman/kotshi/issues/41

**Comment by blackberry2016** [comment] 2018-02-15 04:14
For this kind of data class, use java to avoid this bug temporarily

**Comment by mattbdean** [comment] 2018-02-15 05:54
What I ended up doing was using [AutoValue](https://github.com/google/auto/tree/master/value) + [auto-value-moshi](https://github.com/rharter/auto-value-moshi). You don't need reflection so it's gonna be a lot faster if you need to deserialize a ton of models very quickly like [JRAW](https://github.com/mattbdean/JRAW)

**Comment by autonomousapps** [comment] 2018-03-05 07:50
I can confirm that the [Kotshi](https://github.com/ansman/kotshi) library solves this problem and, moreover, saves us from having to use moshi-kotlin and, therefore, saves us from kotlin-reflect, which contains >10k methods. Which is an important consideration for an Android project.

**Comment by NightlyNexus** [comment] 2018-04-04 06:00
fixed by #475 for users of the KotlinJsonAdapterFactory.

**Closed by NightlyNexus** 2018-04-04 06:00 UTC
Labels: bug

**Comment by AllenCoder** [comment] 2018-05-02 03:54
When to release the latest fix？

**Comment by bradynpoulsen** [comment] 2018-05-10 21:49
I can verify this has been fixed for `KotlinJsonAdapter` in `1.6.0-RC1` for the following sample.

```kotlin
data class Response<Output : Any>(
    val id: String?,
    val result: Output
)

val adapter: JsonAdapter<Response<List<String>>> = moshi.adapter(
    Types.newParameterizedType(
        Response::class.java,  
        Types.newParameterizedType(
            List::class.java, 
            String::class.java
        )
    )
)

adapter.toJson(Response("foo", listOf("bar", "baz"))) // yields: {"id":"foo","result":["bar","baz"]}
```
