### ISSUE TITLE
Too easy to misuse Moshi reflection vs codegen

### ISSUE THREAD

**Issue by ColtonIdle** [square/moshi#887] opened 2019-08-09 17:22 UTC
Confused whether this should be in retrofit or in moshi. Opting to post it here:

I added

```
    implementation 'com.squareup.retrofit2:retrofit:2.6.1'
    implementation 'com.squareup.retrofit2:converter-moshi:2.6.1'
```

Notice that I didn't add any explicit Moshi dependencies.

Now I actually didn't think any of my code would work because I didn't declare any moshi dependencies, but it does.

Now I saw that moshi converter is pulling in moshi. But then I went in and added:

`kapt 'com.squareup.moshi:moshi-kotlin-codegen:1.8.0'`

and I thought this meant I'm using codegen. But I didn't. I apparently still have to add :

`@JsonClass(generateAdapter = true)`

All of this is a long way of saying that a seemingly trivial addition of Moshi (which I did in a large codebase) I expected codegen to work for the past year, but I never noticed it wasn't working since it was using the reflection version.

Is there any way to tell which one is being used? Or enforce that the codegen one is used? You may point to the docs and say that "It says in the docs to use @JsonClass(generateAdapter = true), but I found this line misleading " Enable it by annotating each class that you want to encode as JSON:"

Now I don't want to "encode as JSON", I want to "decode from JSON", so I figured I could leave it out.

I feel like I should explicitly tell it to be reflection or codegen based.

For example, what if I have a nested data class?

```
@JsonClass(generateAdapter = true)
data class Person(
    val nestedPerson: NestedPerson = NestedPerson()
) {
    data class NestedPerson(val person: String = "")
}
```

Is my NestedPerson using reflection? Am I supposed to use:

```
@JsonClass(generateAdapter = true)
data class Person(
    val nestedPerson: NestedPerson = NestedPerson()
) {
    @JsonClass(generateAdapter = true)
    data class NestedPerson(val person: String = "")
}
```

Sorry for the semi-rant. I just hate how I misused moshi for like a year because I thought I was using the reflection based, then I built a sample project and even misused it there and feel like the docs should be clearer or there should be a way to tell what I'm using. Even if the moshi project doesn't decide to fix/clarify this, maybe someone can answer the nested data class question?

**Comment by swankjesse** [comment] 2019-08-09 20:41
Would this have helped?
https://github.com/square/moshi/pull/749

We need a release. My bad.

**Comment by ColtonIdle** [comment] 2019-08-09 20:48
I'm not sure if it would have helped as some of that is going over my head.

A test named "kotlinClassesWithoutAdapterAreRefused" does look promising though! I guess I will wait for the next release and see what happens there.

**Comment by DanteAndroid** [comment] 2019-08-28 03:04
When I didn't add `@JsonClass(generateAdapter = true)` I just get null value from the result moshi parses. And I googled that, someone suggests I add it, then it worked. But the doc doesn't say that.

**Comment by ZacSweers** [comment] 2019-09-11 01:44
#749 should cover this, going to close this out for now

**Closed by ZacSweers** 2019-09-11 01:44 UTC

**Comment by ColtonIdle** [comment] 2019-09-18 12:01
For anyone that finds this in the future. I had some major problems in my project getting this to work correctly, but I think I found the root of the issue. I was using this article https://medium.com/@naturalwarren/kotlin-users-safely-upgrade-to-moshi-c01168a39f79 and it does some really weird things. If deserialization in Moshi fails it seems to fall back onto gson. This is undocumented and causes some weird issues all around.

Make sure that your data class includes `@JsonClass(generateAdapter = true)` for every nested class as well.

e.g.

Turn this

```
@JsonClass(generateAdapter = true)
data class GetProfile(
    val one: List<One> = listOf()
) {
    data class One(
        val two: Two = Two()
    ) {
        data class Two(
            val three: String = ""
        )
    }
}
```

into

```
@JsonClass(generateAdapter = true)
data class GetProfile(
    val one: List<One> = listOf()
) {
    @JsonClass(generateAdapter = true)
    data class One(
        val two: Two = Two()
    ) {
        @JsonClass(generateAdapter = true)
        data class Two(
            val three: String = ""
        )
    }
}
```

**Comment by PramodGarg** [comment] 2020-01-09 13:51
Hey @ColtonIdle , I too am using
https://medium.com/@naturalwarren/kotlin-users-safely-upgrade-to-moshi-c01168a39f79
to use both GSON and Moshi (Code-Gen). 
The error I'm getting is:

Caused by: java.lang.ClassNotFoundException: Didn't find class "feature.bankaccounts.data.model.AccountExpenseResponseJsonAdapter" on path: DexPathList[[zip file "/data ......

**Comment by ColtonIdle** [comment] 2020-01-09 14:53
Maybe @ZacSweers would know, but in my cases I don't believe I was ever getting this?

As an aside... I don't think anyone should follow that article. It's proven to be a pretty bad experience. Things just haven't worked the way they should.
