### ISSUE TITLE
Codegen - TypeAlias for Map doesn't carry types

### ISSUE THREAD

**Issue by yayaa** [square/moshi#558] opened 2018-05-23 16:00 UTC
Having a typealias as;
```kotlin 
typealias InteractionResponseMap = Map<String, InteractionResponse>
```
once this is defined as a value type on a data class, build fails with the following error;
`2 type arguments expected for interface Map<K, out V>`

When I checked the generated code, I can see that adapter generated as;
```kotlin
 private val mapAdapter: JsonAdapter<Map> = moshi.adapter(Map::class.java).nonNull()
```

But when I define the value directly as `Map<String, InteractionResponse>` then it generates as;
```kotlin
private val mapOfStringInteractionResponseAdapter: JsonAdapter<Map<String, InteractionResponse>> =
            moshi.adapter<Map<String, InteractionResponse>>(Types.newParameterizedType(Map::class.java, String::class.java, InteractionResponse::class.java)).nonNull()
```

**Comment by JakeWharton** [comment] 2018-05-23 16:04
Dupe of #547. You can try the latest snapshot to confirm that it's fixed for you.

**Closed by JakeWharton** 2018-05-23 16:04 UTC
