### ISSUE TITLE
java.lang.IllegalArgumentException: Expected a Class, ParameterizedType, or GenericArrayType, but <null> is of type null

### ISSUE THREAD

**Issue by blackberry2016** [square/moshi#428] opened 2018-01-18 10:06 UTC
The same problem.
moshi 1.5.0
moshi-kotlin:1.5.0
kotlin 1.2.20

```java
data class Note constructor(@Json(name = "note_title") var title: String?,
                            @Json(name = "note_star") var star: Long,
                            @Json(name = "note_content") var content: String?)

data class Page<T> constructor(@Json(name = "my_list") var list: List<T>)
```
The following code
```java
@JvmOverloads
fun toJson(obj: Any, type: Type, moshi: Moshi? = null): String {
    val mMoshi = moshi ?: Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
    return mMoshi.adapter<Any>(type).lenient().toJson(obj)
}


val list = listOf(
                Note("note 1", 1024L, "Learn more, sleep more, and eat more-1"),
                Note("note 2", 512L, "Learn more, sleep more, and eat more-2"),
                Note("note 3", 72L, "Learn more, sleep more, and eat more-3"))

toJson(Page(list), Types.newParameterizedType(Page::class.java, Note::class.java))
```
Exception
```java
java.lang.IllegalArgumentException: Expected a Class, ParameterizedType, or GenericArrayType, but <null> is of type null

	at com.squareup.moshi.Types.getRawType(Types.java:167)
	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:83)
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:75)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
	at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
```

**Comment by NightlyNexus** [comment] 2018-01-18 19:36
Duplicate of #309

**Closed by NightlyNexus** 2018-01-18 19:36 UTC
