### ISSUE TITLE
PolymorphicJsonAdapterFactory peek source is invalid error

### ISSUE THREAD

**Issue by Zedorff** [square/moshi#1036] opened 2019-11-22 17:01 UTC
I'm using PolymorphicJsonAdapterFactory for serializing\deserializing of my complex data.

JSON response from the server could have HTML content as a string in it.

While other fields are skipped fine in 

`labelIndex(JsonReader reader)
` method in PolymorphicJsonAdapter

The one with HTML as a value can throw an error in okio PeekSource

`java.lang.IllegalStateException: Peek source is invalid because upstream source was used
`

The most strange thing is that the same model from response could potentially throw an error but this happens not all the time. 

Is there any way to workaround this issue or to fix it somehow?

Thanks!

**Comment by ZacSweers** [comment] 2019-11-25 07:35
I'm not sure this is enough information for us to diagnose. Can you share a minimally reproducible code snippet or project?

**Comment by Zedorff** [comment] 2019-11-25 17:12
Hi @ZacSweers 

Thanks for the quick response.

Unfortunately, I can't share a project or code snippet, it has very complicated logic so there is lot of class that takes part in our business logic.

For now, we've solved it by simply removing HTML from API response, but this is a workaround. 

I'll try to write as much info as I can and if it won't be enough for at least some thoughts of fixing this issue than this ticket could be closed due to lack of information.

What we are using?
1) Paging library with retrofit and moshi as serializer\deserialize
2) Slightly modified PolymorphicJsonAdapterFactory, we've changed how factory stores Class<T> to labelKey mapped data for support of the same Class with different labels, the rest logic of factory were unchanged.
3) Coroutines for async API calls in our paging adaptors.

What we have checked before submitting an issue?
1) Double-checked threads where we're deserializing JSON, and for each JSON we're using the same thread, so this issue is not thread-related.
2) Switched back from PolymorphicJsonAdapterFactory, and it's working as expected, we're facing the issue only while using this factory. (Each type of content had his own list, so we knew exactly how to parse these lists)
3) Checked all data class fields, and the issue only occurs on String field where it's content is pretty big HTML (from 500 and up to tens of thousands of characters)
4) Tried to find content which causes an issue in 100%, but without success, it's random, it can throw an exception on the same model but can parse it fine in another try.

Here is a part of stack trace which may be helpful

`Caused by java.lang.IllegalStateException: Peek source is invalid because upstream source was used
       at okio.PeekSource.read(PeekSource.java:53)
       at okio.RealBufferedSource.indexOfElement(RealBufferedSource.java:397)
       at okio.RealBufferedSource.indexOfElement(RealBufferedSource.java:386)
       at com.squareup.moshi.JsonUtf8Reader.skipQuotedValue(JsonUtf8Reader.java:861)
       at com.squareup.moshi.JsonUtf8Reader.skipValue(JsonUtf8Reader.java:968)
       at com.oshihealth.network.moshi.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.labelValue(PolymorphicJsonAdapterFactory.kt:65)
       at com.oshihealth.network.moshi.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.fromJson(PolymorphicJsonAdapterFactory.kt:55)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
       at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
       at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
       at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
       at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
       at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
       at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
       at com.oshihealth.oshi.ui.activity.base.pagination.BaseDataSource.execute(BaseDataSource.kt:53)`

If you need something more, please let me know, I'll try to provide this information to you

Best regards, Ilya

**Comment by ZacSweers** [comment] 2019-11-25 17:23
Is it something you could share privately?

**Comment by Zedorff** [comment] 2019-11-25 17:25
Unfortunately no, it’s under NDA
25 нояб. 2019 г., 19:23 +0200, Zac Sweers <notifications@github.com>, писал:

**Comment by maciej-kaznowski** [comment] 2019-12-01 19:43
I too am experiencing this problem. I am not using PolymorphicJsonAdapterFactory, however I do call  `JsonAdapter.peek()` (I don't consume the original source when peeking)

It most often appears when experiencing a flaky network. It happens then about  50% of the time. Otherwise I haven't found a reliable way to reproduce it. My content has html in it too, but I'm not sure if that's a correlation. I'll try and capture the exact response body when this issue appears, for the time being here is my stacktrace:

`com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: java.lang.IllegalStateException: Peek source is invalid because upstream source was used
at $[1].data.children[0].data
at $[1].data.children[0].data
at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:94)
at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
at io.reactivex.Observable.subscribe(Observable.java:12267)
at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
at io.reactivex.Observable.subscribe(Observable.java:12267)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764) Caused by: com.squareup.moshi.JsonDataException: java.lang.IllegalStateException: Peek source is invalid because upstream source was used
at $[1].data.children[0].data
at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:94)
at com.innercirclesoftware.reddit_api.comments.LinkWithComments$Adapter.fromJson(LinkWithComments.kt:28)
at java.lang.reflect.Method.invoke(Native Method)
at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:335)
at com.squareup.moshi.AdapterMethodsFactory$4.fromJson(AdapterMethodsFactory.java:233)
at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:90) ... 17 more Caused by: java.lang.IllegalStateException: Peek source is invalid because upstream source was used
at okio.PeekSource.read(PeekSource.kt:42)
at okio.RealBufferedSource.indexOfElement(RealBufferedSource.kt:386)
at okio.RealBufferedSource.indexOfElement(RealBufferedSource.kt:375)
at com.squareup.moshi.JsonUtf8Reader.skipQuotedValue(JsonUtf8Reader.java:861)
at com.squareup.moshi.JsonUtf8Reader.skipValue(JsonUtf8Reader.java:968)
at com.innercirclesoftware.reddit_api.models.AppearsInCommentReplies$Adapter.fromJson(RedditComment.kt:53)
at com.innercirclesoftware.reddit_api.models.AppearsInCommentReplies$Adapter.fromJson(RedditComment.kt:36)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
at com.innercirclesoftware.reddit_api.models.RedditComment$Reply$Adapter.fromJson(RedditComment.kt:140)
at java.lang.reflect.Method.invoke(Native Method)
at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:335)
at com.squareup.moshi.AdapterMethodsFactory$4.fromJson(AdapterMethodsFactory.java:233)
at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:90) ... 22 more
`

**Comment by ZacSweers** [comment] 2020-01-15 03:09
I'm closing this out for now as there's not really enough information in the comments above to help. If you can make a minimally reproducing case, we can look again.

**Closed by ZacSweers** 2020-01-15 03:09 UTC
