### ISSUE TITLE
Unable to build MyObjectJsonAdapter because of kotlinx.android.parcel.RawValue

### ISSUE THREAD

**Issue by coroutineDispatcher** [square/moshi#1077] opened 2020-01-16 13:11 UTC
Hi, 

I have this class:

```
@Entity(tableName = "names_of_creator")
@Parcelize
@JsonClass(generateAdapter = true)
data class Name @JvmOverloads constructor(
    @Json(name = "name")
    @ColumnInfo(name = "arabic_name")
    val arabicName: String,

    @Json(name = "transliteration")
    @ColumnInfo(name = "transliteration")
    val transliteration: String,

    @Json(name = "number")
    @PrimaryKey
    @ColumnInfo(name = "id")
    val number: Int,

    @Json(name = "en")
    @Ignore
    val englishNameMeaning: @RawValue EnglishNameMeaning? = null,

    @ColumnInfo(name = "name_meaning")
    @Transient
    var meaning: String? = ""
) : Parcelable
```

When I try to build it, the compiler yells at me telling:
`'This annotation is not applicable to target 'expression'` -> Pointing at this `@RawValue`:

```
///from code generation
moshi.adapter(@RawValue EnglishNameMeaning::class.java, emptySet(), "englishNameMeaning")
```
I can of course detach my parsing object from my parcelable implementation (just extract data to a new object), but how can I solve this without any other option. Btw this is my `EnglishNameMeaning` class:

```
@JsonClass(generateAdapter = true)
data class EnglishNameMeaning(@Json(name = "meaning") val meaning: String)
```

Versions of Moshi that I'm using:
```
com.squareup.moshi:moshi:1.9.2
com.squareup.moshi:moshi-kotlin:1.9.2
com.squareup.moshi:moshi-kotlin-codegen:1.9.2
```

If that helps, I'm also using moshi-retrofit converter version 2.7.1

Thnx for your time.

**Comment by ZacSweers** [comment] 2020-01-16 15:12
Duplicate of #1033

**Closed by ZacSweers** 2020-01-16 15:12 UTC
