### ISSUE TITLE
Moshi ALWAYS fails to create adapter for ANY obfuscated enum class

### ISSUE THREAD

**Issue by igokoro** [square/moshi#1261] opened 2020-10-23 19:35 UTC
Moshi always fails to create an adapter for any class that directly or indirectly references obfuscated enum class. The resulting stacktrace would look something like the following:
```
2020-10-23 14:52:51.063 8650-8650/dev.igokoro.moshi_enum E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.igokoro.moshi_enum, PID: 8650
    java.lang.AssertionError: Missing field in c.a.a.a
        at b.b.a.r$k.<init>(:283)
        at b.b.a.r$b.a(:68)
        at b.b.a.q.f(:145)
        at b.b.a.c$a.b(:142)
        at b.b.a.c$a.a(:106)
        at b.b.a.q.f(:145)
        at b.b.a.q.e(:105)
        at b.b.a.q.c(:79)
        at dev.igokoro.moshi_enum.MainActivity.E(:27)
        at dev.igokoro.moshi_enum.MainActivity.onCreate(:15)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NoSuchFieldException: A
        at java.lang.Class.getField(Class.java:1604)
        at b.b.a.r$k.<init>(:277)
        at b.b.a.r$b.a(:68) 
        at b.b.a.q.f(:145) 
        at b.b.a.c$a.b(:142) 
        at b.b.a.c$a.a(:106) 
        at b.b.a.q.f(:145) 
        at b.b.a.q.e(:105) 
        at b.b.a.q.c(:79) 
        at dev.igokoro.moshi_enum.MainActivity.E(:27) 
        at dev.igokoro.moshi_enum.MainActivity.onCreate(:15) 
        at android.app.Activity.performCreate(Activity.java:8000) 
        at android.app.Activity.performCreate(Activity.java:7984) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```
or deobfuscated
```
2020-10-23 14:52:51.063 8650-8650/dev.igokoro.moshi_enum E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.igokoro.moshi_enum, PID: 8650
    java.lang.AssertionError: Missing field in c.a.a.a
        at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.<init>(:283)
        at com.squareup.moshi.StandardJsonAdapters$1.create(:68)
        at com.squareup.moshi.Moshi.adapter(:145)
        at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(:142)
        at com.squareup.moshi.ClassJsonAdapter$1.create(:106)
        at com.squareup.moshi.Moshi.adapter(:145)
        at com.squareup.moshi.Moshi.adapter(:105)
        at com.squareup.moshi.Moshi.adapter(:79)
        at dev.igokoro.moshi_enum.MainActivity.java(:27)
        at dev.igokoro.moshi_enum.MainActivity.onCreate(:15)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NoSuchFieldException: A
        at java.lang.Class.getField(Class.java:1604)
        at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.<init>(:277)
        at b.b.a.r$b.a(:68) 
        at b.b.a.q.f(:145) 
        at b.b.a.c$a.b(:142) 
        at b.b.a.c$a.a(:106) 
        at b.b.a.q.f(:145) 
        at b.b.a.q.e(:105) 
        at b.b.a.q.c(:79) 
        at dev.igokoro.moshi_enum.MainActivity.E(:27) 
        at dev.igokoro.moshi_enum.MainActivity.onCreate(:15) 
        at android.app.Activity.performCreate(Activity.java:8000) 
        at android.app.Activity.performCreate(Activity.java:7984) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

Sample project to reproduce the issue: https://github.com/igokoro/moshi-obfuscated-enums

The root cause is that `EnumJsonAdapter` makes an assumption that entries from an array returned by `Class.getEnumConstants()` are always matching field names in the enum class. This does not hold true after the obfuscation that keeps enum constants unchanged but renames fields. (Looking into https://stackoverflow.com/questions/33189249/how-to-tell-proguard-to-keep-enum-constants-and-fields looks like such implementation originates at least from jaxb?)

The workaround is, of course, to exclude affected enums from obfuscation. 
But since the above will happen with any obfuscated enum:
* Is it possible to change `EnumJsonAdapter` to better tolerate obfuscated enums?
* Consider adding docs to the proguard section to describe the behavior and suggest an upfront solution/workaround. This can save a lot of time!

**Comment by igokoro** [comment] 2020-10-23 19:40
This issue is probably the same problem as in #1240. Opening a new one here to describe the issue from a different perspective: it affects any obfuscate enum, so it must affect a considerable amount of people.

**Comment by ZacSweers** [comment] 2020-10-23 19:44
Same issue, please don't duplicate. We've invites contributions before to improve readme wording, do you want to send a PR? The best solution is annotating them with `@JsonClass(generateAdapter = false)`

**Comment by igokoro** [comment] 2020-10-26 15:10
@ZacSweers, #1240 was closed. Yet the actual problem remains. So, I opened this issue. I can certainly try submitting the PR for the documentation update - hold off with closing this one.

Took me a little bit of time to understand why `@JsonClass` fixes the problem but I finally found the following:
```
# Enum field names are used by the integrated EnumJsonAdapter.
# values() is synthesized by the Kotlin compiler and is used by EnumJsonAdapter indirectly
# Annotate enums with @JsonClass(generateAdapter = false) to use them with Moshi.
-keepclassmembers @com.squareup.moshi.JsonClass class * extends java.lang.Enum {
    <fields>;
    **[] values();
}
```

**Comment by ZacSweers** [comment] 2021-02-01 23:18
Duplicate of #1240 and PR was never finished

**Closed by ZacSweers** 2021-02-01 23:18 UTC
