### ISSUE TITLE
Error: "@JsonClass can't be applied to ..: must be a Kotlin class"

### ISSUE THREAD

**Issue by RahulSDeshpande** [square/moshi#859] opened 2019-06-01 05:45 UTC
I am using Moshi & Moshi Kotlin Codegen libs as below:
* **com.squareup.moshi:moshi:1.8.0**
* **com.squareup.moshi:moshi-kotlin-codegen:1.8.0**

Here is my entity class:
```java
package com.rahulografy.data.entities

import com.rahulografy.domain.entities.Giphy
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class GiphyEntity(
    val id: String,
    val images: ImagesEntity
) {
    constructor(gif: Giphy) : this(gif.id, ImagesEntity(gif.images))

    fun unwrap() = Giphy(
        id, "", images.unwrap(), null
    )
}
```

The app initially used to get successfully compiled & executed.
**But since yesterday, for some unknown reason, I am getting this error when I try to build the project.**

```java
error: @JsonClass can't be applied to com.rahulografy.data.entities.GiphyEntity:
must be a Kotlin class
public final class GiphyEntity {
             ^
```

When I checked the **/build/tmp/kapt3/stubs/debug/com/rahulografy/data/entities/** folder, I see that the code generated for these entity classes are actually in **Java** & not **Kotlin**.

Here is the screen-grab.
<img width="934" alt="Screenshot 2019-06-01 at 11 02 21 AM" src="https://user-images.githubusercontent.com/6327731/58744223-68684680-845d-11e9-8f12-c562b58214b4.png">

I tried reading the instructions in Readme.md file of this lib, but didn't get the solid solution.

A quick help/guide would really be appreciated 💯

Thanks & cheers :)

**Comment by RahulSDeshpande** [comment] 2019-06-01 07:34
I believe its somehow related to the Gradle Wrapper version.

It is working when I downgraded the Gradle Wrapper version from:
**gradle-5.1.1-all.zip** to **gradle-4.10.1-all.zip**

:( Its strange!!

**Comment by ZacSweers** [comment] 2019-06-18 06:25
Goign to close this out since you have a workaround. Please file a bug on gradle if you believe the issue is related to the build system

**Closed by ZacSweers** 2019-06-18 06:25 UTC

**Comment by RahulSDeshpande** [comment] 2019-07-02 19:34
Sure!
Thanks, @ZacSweers :)

**Comment by hoangnguyen92dn** [comment] 2020-03-25 11:14
I have same issue but with sealed class, gradle version on my current project is `5.6.4`

```
sealed class A {
    data class A1(val a: String) : A() // It's working fine

    object B(): A() // Error: @JsonClass can't be applied .... must be a Kotlin class

    object C(): A() // Error: @JsonClass can't be applied .... must be a Kotlin class
}
```

Any specific reason for this case? Thank you.

**Comment by rharter** [comment] 2020-03-27 15:11
`object` isn't a class, it's an object.
