### ISSUE TITLE
Moshi 1.12.0 with Kotlin 1.6.0 throws IllegalStateException during code generation

### ISSUE THREAD

**Issue by stephan-mediamonks** [square/moshi#1429] opened 2021-11-18 09:20 UTC
Steps to reproduce:

1. Start a new project in Android Studio
2. Make sure the project build.gradle specifies "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0"
3. In the app build.gradle, add `implementation 'com.squareup.moshi:moshi:1.12.0'` and `kapt 'com.squareup.moshi:moshi-kotlin-codegen:1.12.0'`
4. Create a new `data Class` with annotation `@JsonClass(generateAdapter = true)`
5. Try to build the project, observe this fails

Building with `--stacktrace` provides  a long stacktrace, the last part of which is listed below:
```
Caused by: java.lang.IllegalStateException: Could not parse metadata! This should only happen if you're using Kotlin <1.1.
        at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.readKotlinClassMetadata(KotlinPoetMetadata.kt:89)
        at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.toImmutableKmClass(KotlinPoetMetadata.kt:119)
        at com.squareup.moshi.kotlin.codegen.MoshiCachedClassInspector.toImmutableKmClass(MoshiCachedClassInspector.kt:37)
        at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:139)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:148)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:114)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:188)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
```

Attached is a project which (on my machine) displays this behaviour.

Environmental settings:
- MacBook Pro running Big Sur
- Android Studio Arctic Fox
- JDK 11 from Android Studio
[TestMoshiKotlin16.zip](https://github.com/square/moshi/files/7561590/TestMoshiKotlin16.zip)

**Comment by n0m0r3pa1n** [comment] 2021-11-18 09:28
I guess this fixes it: https://github.com/square/moshi/commit/73553286fb482040990c9efadd829faf849b676e
The question is when it will be available in maven :)

**Comment by JakeWharton** [comment] 2021-11-18 12:07
Dupe of #1368

**Closed by JakeWharton** 2021-11-18 12:07 UTC
Labels: bug
