### ISSUE TITLE
Adapter for platform value class is not picked up

### ISSUE THREAD

**Issue by StephanSchuster** [square/moshi#1536] opened 2022-05-03 08:05 UTC
I tried a lot and [read a lot](https://github.com/square/moshi#alternate-type-adapters-with-jsonqualifier) but did not get anywhere so far with mapping from Jetpack Compose Color (a platform value class) to JSON and vice versa. It works when representing Color as Int but that's not what I want.

I would expect that it is possible to directly use Color with a custom adapter as shown below. However, this results in `java.lang.IllegalArgumentException: Platform class androidx.compose.ui.graphics.Color requires explicit JsonAdapter to be registered`. As far as I can see, the reason is that the generated adapter for `Test` looks for an adapter with type `Color::class.java` while my custom `ColorAdapter` gets registered as `long` because of `Color` being a value class.

Is this a bug, a missing feature or did I miss something?

```
{
  "color": "#00FF00"
}
```
```
@JsonClass(generateAdapter = true)
data class Test(
    val color: Color
)
```
```
class ColorAdapter {

    @ToJson
    fun toJson(color: Color): String {
        ...
    }

    @FromJson
    fun fromJson(json: String): Color {
        ...
    }
}
```
`val adapter = Moshi.Builder().add(ColorAdapter(context)).build().adapter(Test::class.java)`

**Comment by ZacSweers** [comment] 2022-05-03 08:28
Dupe of #1170

**Closed by ZacSweers** 2022-05-03 08:28 UTC
Labels: bug

**Comment by StephanSchuster** [comment] 2022-05-03 09:12
@ZacSweers : Thanks for your immediate response. I saw this other issue before but did not identify it as a 100% dupe. Fine, if this is the case.

Maybe you have time to answer 2 quick questions:
- What is the cleanest workaround at the moment for my use case?
  - E.g.: Is it possible to explicitly state the type for which my custom adapter should be called (Color instead of Int)?
  - If not, I assume representing Color as Int with annotation as stated in the Moshi docs is my only option, right?
- Do you already have a rough idea when value/inline classes will be supported?
