### ISSUE TITLE
Unable to create @Body converter for class 

### ISSUE THREAD

**Issue by NicolasLeveque** [square/moshi#879] opened 2019-07-10 10:20 UTC
Hello,
I try to use Moshi with Retrofit, I used Yelp to generate calls and objects (https://github.com/Yelp/swagger-gradle-codegen)

I receive an error : 
`Unable to create @Body converter for class ObjectRequest (parameter #1)`

```
@POST("/xxxxxxx")
fun call(@Body object: ObjectRequest): Single<ObjectResponse>
```

```
class ObjectRequest {
    @Json(name = "field")
    var field: String? = null
}
```
``` 1st try
Retrofit.Builder()
            .baseUrl("xxxxxxxxxxxxxx")
            .addConverterFactory(MoshiConverterFactory.create())
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .client(okHttpClient)
            .build()
            .create(xxxxxx::class.java)
```
``` 2nd try
    val moshi = Moshi.Builder()
            .add(XNullableAdapterFactory())
            .add(KotlinJsonAdapterFactory())
            .add(TypesAdapterFactory())
            .build()

Retrofit.Builder()
            .baseUrl("xxxxxxxxxxxxxx")
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .client(okHttpClient)
            .build()
            .create(xxxxxx::class.java)
```

**Comment by JakeWharton** [comment] 2019-07-10 12:38
Please include the full stacktrace

**Comment by JakeWharton** [comment] 2019-07-10 12:39
Dupe of https://github.com/square/retrofit/issues/3157

**Closed by JakeWharton** 2019-07-10 12:39 UTC
