### ISSUE TITLE
ULong field ignores manual code generation keys 

### ISSUE THREAD

**Issue by PhilipDukhov** [square/moshi#1576] opened 2022-09-08 11:39 UTC
I found [this issue](https://github.com/square/moshi/issues/832), which says "inline classes yet since its an experimental feature", which is not true since 1.5.

If inline classes are still not supported, it should fail at build time, instead of what's happening now.

If class marked for code generation with `JsonClass` has `ULong` field, all `@Json(name = ` parameters for other fields are ignored, and generated adapter has `options` generated from field names instead, e.g.
```
JsonReader.Options.of("intField", "ulongField")
```
instead of expected
```
JsonReader.Options.of("int_field", "ulong_field")
```

Seems like code generation is not working for test classes(at least with default setup), not sure how to construct an isolated test in this case.

I was able to reproduce the issue with these class in main part:
```
@JsonClass(generateAdapter = true)
data class TestULong(
    @Json(name = "int_field") val intField: Int,
    @Json(name = "ulong_field") val ulongField: ULong,
)
```
And this test:
```
@OptIn(ExperimentalStdlibApi::class)
class MoshiBugReport {
    val json = "{\"int_field\":1,\"ulong_field\":1}"

    val moshi = Moshi.Builder()
        .add(ULong::class.java, ULongJsonAdapter().nullSafe())
        .build()

    @Test
    fun failingTest() {
        val adapter = moshi.adapter<TestULong>()
        val instance = adapter.fromJson(json)!!

        assertEquals(adapter.toJson(instance), json)
    }

    class ULongJsonAdapter : JsonAdapter<ULong>() {
        override fun fromJson(reader: JsonReader): ULong =
            reader.nextString().toULong()

        override fun toJson(writer: JsonWriter, value: ULong?) {
            writer.value(value?.toString())
        }
    }
}
```
Sample project: 
[MoshiULongTest.zip](https://github.com/square/moshi/files/9526446/MoshiULongTest.zip)

**Comment by ZacSweers** [comment] 2022-09-08 23:29
Dupe of #1170

**Closed by ZacSweers** 2022-09-08 23:29 UTC
Labels: bug
