### ISSUE TITLE
Moshi slower than Gson reading quoted values.

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#509] opened 2018-04-24 00:22 UTC
Ran the following in large loops.
```java
try (com.google.gson.stream.JsonReader reader = new com.google.gson.stream.JsonReader(
    new InputStreamReader(Foo.class.getClassLoader().getResourceAsStream("foo.json"), UTF_8))) {
  reader.setLenient(true);
  reader.beginArray();
  while (reader.hasNext()) {
    reader.nextLong();
  }
  reader.endArray();
}
```
vs.
```java
try (JsonReader reader = JsonReader.of(
    Okio.buffer(Okio.source(Foo.class.getClassLoader().getResourceAsStream("foo.json"))))) {
  reader.setLenient(true);
  reader.beginArray();
  while (reader.hasNext()) {
    reader.nextLong();
  }
  reader.endArray();
}
```
With foo.json containing a huge array of single-quoted longs, Gson was about 25% faster. With foo.json containing unquoted longs, Moshi was about as fast as Gson.

I found this performance degradation in other quoted values, like nextString and nextName, too.

I suspect it is the performance of `nextQuotedValue` and BufferedSource's `indexOfElement`. (I will have to learn how to use real measurement tools, but I wanted to file here to remember to get back to this after finding this last Friday.)

**Comment by swankjesse** [comment] 2018-04-28 16:59
@Armaxis ooh, interesting. We can make that faster. Could you tell me how many fields your target classes have? `select()` is optimized for relatively small sets of names: ~12 or fewer.

**Comment by Armaxis** [comment] 2018-04-30 18:41
Looked more into the issue - definitely `Buffer#select()` take a lot of time when options include a lot of fields. For 50+ fields I see the time spent in this method is up to **0.13ms** per call. 
Should this be created as issue on okio page? You guys are rewriting it in Kotlin now, maybe it's a good time to review this method 😃

**Comment by swankjesse** [comment] 2018-04-30 19:36
Yeah, we can make it faster for large numbers of fields. Could you share a sample JSON message and the type it maps to? Or perhaps just the min/mean/max lengths of these fields and whether they share a common prefix?

**Comment by Armaxis** [comment] 2018-04-30 19:58
@swankjesse check out my previous comment, I shared a project with sample Jon and structure. The big classes are ProgramData and VideoOnDemandData

**Comment by swankjesse** [comment] 2018-05-08 03:40
Good news. I’ve [started implementing](https://github.com/square/okio/compare/jwilson.0507.trieselect?expand=1) a trie-based select() and the performance is better. From the [SelectBenchmark](https://github.com/square/okio/pull/427), these are JVM numbers for a varying number of options:

```
linear    4     88.197 ± 0.519  us/op
trie      4     87.662 ± 0.399  us/op
linear    8    139.014 ± 0.787  us/op
trie      8     97.934 ± 0.434  us/op
linear   16    224.262 ± 3.278  us/op
trie     16    123.960 ± 0.360  us/op
linear   32    329.384 ± 1.867  us/op
trie     32    155.407 ± 1.191  us/op
linear   64    620.990 ± 5.640  us/op
trie     64    183.513 ± 0.724  us/op
```

The PR is not quite ready yet. I need to implement both select() and selectPrefix(). That should be straightforward and the performance numbers should carry over.

**Comment by Armaxis** [comment] 2018-05-08 04:17
@swankjesse that's impressive! And the fact that even on 4 options it still performs better than linear suggests that linear can be removed completely, nice! 

Can't wait to try it out on my json sample. This change can mean that all my headache with parsing will be gone. 😄

**Comment by swankjesse** [comment] 2018-05-10 00:40
@Armaxis thanks for your help! I just merged an update to Okio that changes Options to use a [trie](https://github.com/square/okio/pull/432) rather than a linear search. If your benchmarking harness is still handy, could you try running with the latest Okio?

**Comment by Armaxis** [comment] 2018-05-10 01:00
@swankjesse will do. Which version of okio should I include in Gradle file? Is it in 1.15 snapshot or 2.0?

**Comment by swankjesse** [comment] 2018-05-10 02:07
Just checked and our snapshots are [currently stale](https://github.com/square/okio/issues/435). If you’re comfortable building a .jar yourself you can do that, otherwise I’ll ping ya when we get snapshots online again.

**Comment by Armaxis** [comment] 2018-05-10 16:50
I'll wait for a snapshot, thanks!

**Comment by Armaxis** [comment] 2018-05-11 18:49
Ok, I ran some tests and with 1.15 parsing is **SLOWER** than with 1.14.

On 1.14 it takes **3.1sec** to parse file, on 1.15 - **3.3sec**

Here are some flame charts + bottom up. You can see that `selectName()` no longer takes a lot of time, but some other methods do. Maybe it's because of unrelated changes due to switch to Kotlin?

### Okio 1.15 (with trie)
![1-15-flame](https://user-images.githubusercontent.com/2152942/39941382-3e865edc-5511-11e8-9b0d-153bdfeda6f2.jpg)
![1-15-bottomup](https://user-images.githubusercontent.com/2152942/39941383-407a3394-5511-11e8-98cb-737e9ee13cad.jpg)
### Okio 1.14
![1-14-flame](https://user-images.githubusercontent.com/2152942/39941389-42cc481c-5511-11e8-9d49-2583723e3560.jpg)
![1-14-bottomup](https://user-images.githubusercontent.com/2152942/39941391-44d13ee2-5511-11e8-9c8f-6f7d9e6003fa.jpg)

**Comment by swankjesse** [comment] 2018-05-11 21:54
This is fantastic. Thanks for the flame graphs. Definitely looks like Kotlin is to blame for the regression.

I'll backport the select improvement to 1.x.

We'll figure out why Kotlin is regressing. Probably some simple things like unexpected boxing or null checks.

**Comment by Armaxis** [comment] 2018-05-11 22:15
@swankjesse you're welcome! :) It looks like the bottleneck is in [`checkOffsetAndCount`](https://github.com/square/okio/blob/3833a497a4e85640ce40f559cca93e14f7588a00/okio/src/main/kotlin/okio/Util.kt#L21). Good that we caught it before the library release 😃 

The decompiled to java version of the method looks like this:
```java
public static final void checkOffsetAndCount(long size, long offset, long byteCount) {
   if ((offset | byteCount) < 0L || offset > size || size - offset < byteCount) {
      throw (Throwable)(new ArrayIndexOutOfBoundsException("size=" + size + " offset=" + offset + " byteCount=" + byteCount));
   }
}
```

**Comment by Armaxis** [comment] 2018-05-12 00:46
The only guess I have is either it's because of the `0L` that takes 16 bytes or the fact that we do operations on long?

Here's bytecode of the function that ended up in my apk, hope it helps..

```
.method public static final checkOffsetAndCount(JJJ)V
    .registers 10
    .param p0, "size"    # J
    .param p2, "offset"    # J
    .param p4, "byteCount"    # J

    .line 22
    or-long v0, p2, p4

    const-wide/16 v2, 0x0

    cmp-long v0, v0, v2

    if-ltz v0, :cond_14

    cmp-long v0, p2, p0

    if-gtz v0, :cond_14

    sub-long v0, p0, p2

    cmp-long v0, v0, p4

    if-gez v0, :cond_13

    goto :goto_14

    .line 25
    :cond_13
    return-void

    .line 23
    :cond_14
    :goto_14
    new-instance v0, Ljava/lang/ArrayIndexOutOfBoundsException;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string v2, "size="

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1, p0, p1}, Ljava/lang/StringBuilder;->append(J)Ljava/lang/StringBuilder;

    const-string v2, " offset="

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1, p2, p3}, Ljava/lang/StringBuilder;->append(J)Ljava/lang/StringBuilder;

    const-string v2, " byteCount="

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1, p4, p5}, Ljava/lang/StringBuilder;->append(J)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-direct {v0, v1}, Ljava/lang/ArrayIndexOutOfBoundsException;-><init>(Ljava/lang/String;)V

    check-cast v0, Ljava/lang/Throwable;

    throw v0
.end method
```

**Comment by Armaxis** [comment] 2018-05-12 01:55
Single call to java equivalent of `checkOffsetAndCount` takes about 1000ns on this device, so it shouldn't be an issue.. 

Anything suspicious in how we call the method from `Buffer` class? This `invoke-static/range` looks ok?
```
...
const-string v0, "charset"
invoke-static {p3, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V
.line 651
iget-wide v1, p0, Lokio/Buffer;->size:J
const-wide/16 v3, 0x0
move-wide v5, p1
invoke-static/range {v1 .. v6}, Lokio/Util;->checkOffsetAndCount(JJJ)V
...
```

**Comment by swankjesse** [comment] 2018-05-13 02:40
@Armaxis here’s a snapshot with tries but no Kotlin:

okio-1.15.0-20180513.011724-12.jar
--

**Comment by Armaxis** [comment] 2018-05-14 18:18
@swankjesse yup, it was Kotlin's fault. Here's test results without Kotlin:

**
Moshi - 3054ms (no trie)
Moshi - 2063ms (with trie)
GSON - 1052ms (default, with reflection)
GSON - 866ms (custom adapters with [Stag](https://github.com/vimeo/stag-java))**

Here's some diagrams as well. `JsonUtf8Reader.nextNonWhitespace()` is not taking 64% if total time.

![okio-no-kotlin-flame](https://user-images.githubusercontent.com/2152942/40015389-0f1e018c-5768-11e8-971e-04267081fff4.jpg)
![okio-no-kotlin-bottomup](https://user-images.githubusercontent.com/2152942/40015396-151215a6-5768-11e8-9207-ddf91cf5e6db.jpg)

**Comment by swankjesse** [comment] 2018-05-14 18:36
Your JSON is pretty-printed? That's a case we can fix fast.

**Comment by Armaxis** [comment] 2018-05-14 18:38
Yes, it is. I remember I did some testing with condensed version of Json and it was faster. But our server always returns pretty print version though..

**Comment by Armaxis** [comment] 2018-05-14 19:07
Tried with Json file that is **condensed to single line** (no whitespaces). Moshi parsing time **with trie** went down **from 2063ms to 1375ms**. 

Charts:
![condensed flame](https://user-images.githubusercontent.com/2152942/40017833-6331e5c0-576f-11e8-96bc-052258476d0a.jpg)
![condensed bottomup](https://user-images.githubusercontent.com/2152942/40017836-647f9332-576f-11e8-9599-dff7fa2305c7.jpg)

**Comment by Armaxis** [comment] 2018-07-16 16:34
I believe the fix with trie select is now in [Okio 1.14.1](https://github.com/square/okio/compare/okio-parent-1.14.1...master). Is there going to be more optimizations done related to this issue?

I will be testing performance on my side meanwhile

**Comment by neiljaywarner** [comment] 2019-06-12 16:01
@swankjesse is this fixed? thanks

**Comment by ZacSweers** [comment] 2019-06-18 05:48
the trie-based implementation has been in place for awhile, and I believe even backported to Okio 1.x if you haven't updated yet (deferring to Jesse for confirmation)

**Comment by swankjesse** [comment] 2019-06-18 10:32
It's a problem with pretty-printing. We're not particularly efficient about skipping whitespace, and making that faster makes other JSON slower. It's weird to optimize for pretty printed JSON.

**Comment by ZacSweers** [comment] 2019-09-11 08:03
@swankjesse can we close this?

**Closed** 2019-09-11 11:22 UTC
