### ISSUE TITLE
Creating a JsonAdapter<List<T>> the first time around is (very) slow

### ISSUE THREAD

**Issue by zoltish** [square/moshi#492] opened 2018-04-08 07:27 UTC
I really cant recall this being so slow when I used Moshi earlier on; perhaps Im doing something wrong?

My model is just 3 string fields in this case, parsing the json is fast, but creating the adapter is very slow (~500 ms)

**Code:**

```
moshi =  Moshi.Builder()
                .add(KotlinJsonAdapterFactory())
                .build()
```

```
    fun <T> parseList(rawResource: Int, modelClass: Class<T>): List<T> {
        val adapter = createListAdapter(modelClass)
        val source = createBufferedSource(rawResource)
        return adapter.fromJson(source)!!
    }
```
```
   private fun createBufferedSource(rawResource: Int): BufferedSource {
        return Okio.buffer(Okio.source(context.resources.openRawResource(rawResource)))
    }
```
```
   private fun <T> createListAdapter(modelClass: Class<T>): JsonAdapter<List<T>> {
        val type = createListType(modelClass)
        return moshi.adapter(type)
    }
```

```
    private fun <T> createListType(modelClass: Class<T>): Type {
        return Types.newParameterizedType(List::class.java, modelClass)
    }
```

```
class BodypartJson(val uuid: String,
                   val name: String,
                   val hexColor: String)
```

**Comment by NightlyNexus** [comment] 2018-04-08 07:53
(probably want to close that BufferedSource, btw.)

my guess is the of the initialization of the Kotlin full reflection library is slow.
possible duplicate of #362

**Comment by NightlyNexus** [comment] 2018-04-08 07:56
if this is measurably a problem for your Kotlin usage, you might consider using an annotation processor to generate JsonAdapters for your Kotlin types. See [Kotshi](https://github.com/ansman/kotshi/) and stay tuned for [this](https://github.com/square/moshi/tree/master/kotlin-codegen/).

**Comment by zoltish** [comment] 2018-04-08 08:07
@NightlyNexus Thanks for the tip about closing the source, totally missed it! Ill play around with Kotshi 👍

**Comment by zoltish** [comment] 2018-04-08 17:46
@NightlyNexus Theres actually no difference when using it together with Kotshi :( I can verify that the adapters are generated and used.

**Comment by swankjesse** [comment] 2018-04-08 19:25
Profile it?

**Comment by swankjesse** [comment] 2018-05-04 19:18
No action to take on this.

**Closed by swankjesse** 2018-05-04 19:18 UTC
