### ISSUE TITLE
Exception while generating adapter for nested classes with the same name as enclosing class

### ISSUE THREAD

**Issue by acsbendi** [square/moshi#1112] opened 2020-03-21 13:19 UTC
When I try to generate adapters for the following class structure using kapt in Android Studio, I get an exception:
```kotlin
package com.example.kotlinserializationtest

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class A(
    val a: A
) {
    @JsonClass(generateAdapter = true)
    data class A(
        val value: Boolean = false
    )
}
```

The exception:
```
java.lang.IllegalStateException: No type element found for: com.example.kotlinserializationtest.A.A.
```

The nesting does not have to be immediate, for example:
```kotlin
package com.example.kotlinserializationtest

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class A(
    val b: B
) {
    @JsonClass(generateAdapter = true)
    data class B(
        val c: C
    ){
        @JsonClass(generateAdapter = true)
        data class C(
            val a: A
        ){
            @JsonClass(generateAdapter = true)
            data class A(
                val value: Boolean = false
            )
        }
    }
}
```
fails with a similar exception too:
```
java.lang.IllegalStateException: No type element found for: com.example.kotlinserializationtest.A.B.C.A.
```

I use the latest version, 1.9.2 with Kotlin 1.3.70.

**Comment by swankjesse** [comment] 2020-09-26 02:09
Duplicate of https://github.com/square/moshi/issues/1143

**Closed by swankjesse** 2020-09-26 02:09 UTC
